name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.dockerignore'
      - '.github/**'
      - '.github/workflows/**'

concurrency:
  group: build
  cancel-in-progress: false

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read    
    steps:
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Prepare Docker build
        id: prepare
        run: |
        
          PLATFORMS="linux/amd64,linux/arm64"
          VERSION="${{ vars.MAJOR }}.${{ vars.MINOR }}"
          
          TAGS=()
          TAGS=("${{ secrets.DOCKERHUB_REPO }}:latest")
          TAGS+=("${{ secrets.DOCKERHUB_REPO }}:${VERSION}")
          TAGS+=("ghcr.io/${{ github.repository }}:latest")
          TAGS+=("ghcr.io/${{ github.repository }}:${VERSION}")
          
          echo "tags=${TAGS[@]}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "docker_platforms=${PLATFORMS}" >> $GITHUB_OUTPUT
          echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
      -
        name: Login into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build Docker image
        run: |
        
          TAGS=(${{ steps.prepare.outputs.tags }})

          echo "Build date: ${{ steps.prepare.outputs.build_date }}"
          echo "Docker platform: ${{ steps.prepare.outputs.docker_platforms }}"
          echo "Tags: ${{ steps.prepare.outputs.tags }}"

          docker buildx build --platform ${{ steps.prepare.outputs.docker_platforms }} \
            --output "type=image,push=true" \
            --progress=plain \
            --build-arg "BUILD_ARG=${GITHUB_RUN_ID}" \
            --build-arg "VERSION_ARG=${{ steps.prepare.outputs.version }}" \
            --build-arg "DATE_ARG=${{ steps.prepare.outputs.build_date }}" \
            --build-arg "VCS_REF=${GITHUB_SHA::8}" \
            $(printf "%s" "${TAGS[@]/#/ --tag }" ) .
      -
        name: Clear Docker credentials
        run: |
          rm -f ${HOME}/.docker/config.json
      -
        name: Create a release
        uses: action-pack/github-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          tag: "v${{ steps.prepare.outputs.version }}"
          title: "v${{ steps.prepare.outputs.version }}"
      -
        name: Increment version variable
        uses: action-pack/bump@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Push to Gitlab mirror
        uses: action-pack/gitlab-sync@v3
        with:
          url: ${{ secrets.GITLAB_URL }}
          token: ${{ secrets.GITLAB_TOKEN }}
          username: ${{ secrets.GITLAB_USERNAME }}
