on: [workflow_call]
name: "Check"
permissions: {}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        cache: false
        go-version: '1.21.6'

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
          version: latest
          working-directory: src
          args: --out-format=colored-line-number

    - name: Run staticcheck
      uses: dominikh/staticcheck-action@v1
      with:
        version: latest
        install-go: false
        working-directory: src

    - name: Run Go vet
      run: go vet ./...
      working-directory: src

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        ignore: DL3008
        failure-threshold: warning
