on: [workflow_dispatch]
name: "Test"
permissions: {}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        cache: false
        go-version: '1.21'
        
    - name: Run Go vet
      run: go vet ./...
      working-directory: src
      
    - name: Run staticcheck
      uses: dominikh/staticcheck-action@v1
      with:
        version: latest
        install-go: false
        working-directory: src
      
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
          version: latest
          working-directory: src
