on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.go'
      - 'Dockerfile'
      - '.github/workflows/test.yml'
      - '.github/workflows/check.yml'

name: "Test"
permissions: {}

jobs:
  check:
    name: Test
    uses: ./.github/workflows/check.yml
