on: [workflow_dispatch]
name: "Test"
permissions: {}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Static check
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1"
        install-go: false
        working-directory: src

    - name: Run Go vet
      run: go vet ./...
      working-directory: src
