on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**/*.go"
      - "**/go.mod"
      - "**/go.sum"
      - "Dockerfile"
      - ".github/workflows/*.yml"

name: "Test"
permissions: {}

jobs:
  check:
    name: Test
    uses: ./.github/workflows/check.yml
